const stories = {
    // قصص النساء في القرآن
    1: {
        title: 'قصص النساء في القرآن',
        description: 'قصص نساء عظيمات ذكرن في القرآن، تعلم الصبر والإيمان للأطفال بأسلوب ممتع.',
        episodes: [
            { num: '0', title: 'مقدمه الحلقه', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Women_Stories%20from_Quran/Women_Stories_from_QuranWomen_Stories_from_Quran_intro.mp4', eps_des: '' },
            { num: '00', title: 'خاتمه الحلقه', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Women_Stories%20from_Quran/Women_Stories_from_Quran%20_outro.mp4', eps_des: '' },
            { num: 1, title: 'السيدة حواء أم البشر - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Women_Stories%20from_Quran/Women_Stories_from_Quran_eps1.mp4', eps_des: 'قصة خلق حواء ودورها كأم البشرية.' },
            { num: 2, title: 'السيدة حواء أم البشر - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Women_Stories%20from_Quran/Women_Stories_from_Quran_eps2.mp4', eps_des: 'استكمال قصة حواء وصبرها في الجنة.' },
            { num: 3, title: 'امرأة نوح - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Women_Stories%20from_Quran/Women_Stories_from_Quran_eps3.mp4', eps_des: 'قصة امرأة نوح ودعوتها للإيمان.' },
            { num: 4, title: 'امرأة نوح - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Women_Stories%20from_Quran/Women_Stories_from_Quran_eps4.mp4', eps_des: 'تحديات امرأة نوح أمام الطوفان.' },
            { num: 5, title: 'امرأة نوح - ج 3', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Women_Stories%20from_Quran/Women_Stories_from_Quran_eps5.mp4', eps_des: 'عبرة من قصة امرأة نوح في الإيمان.' },
            { num: 6, title: 'امرأة فرعون - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Women_Stories%20from_Quran/Women_Stories_from_Quran_eps6.mp4', eps_des: 'قصة آسية وإيمانها في قصر فرعون.' },
            { num: 7, title: 'امرأة فرعون - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Women_Stories%20from_Quran/Women_Stories_from_Quran_eps7.mp4', eps_des: 'صبر آسية أمام ظلم فرعون.' },
            { num: 8, title: 'امرأة فرعون - ج 3', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Women_Stories%20from_Quran/Women_Stories_from_Quran_eps8.mp4', eps_des: 'معجزات موسى ودعم آسية له.' },
            { num: 9, title: 'امرأة فرعون - ج 4', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Women_Stories%20from_Quran/Women_Stories_from_Quran_eps9.mp4', eps_des: 'دعاء آسية للجنة وصبرها.' },
            { num: 10, title: 'امرأة فرعون - ج 5', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Women_Stories%20from_Quran/Women_Stories_from_Quran_eps10.mp4', eps_des: 'نهاية آسية كمثال للإيمان.' },
            { num: 11, title: 'امرأة العزيز - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Women_Stories%20from_Quran/Women_Stories_from_Quran_eps11.mp4', eps_des: 'قصة زليخا وإغراء يوسف.' },
            { num: 12, title: 'امرأة العزيز - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Women_Stories%20from_Quran/Women_Stories_from_Quran_eps12.mp4', eps_des: 'محاولات زليخا وصبر يوسف.' },
            { num: 13, title: 'امرأة العزيز - ج 3', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Women_Stories%20from_Quran/Women_Stories_from_Quran_eps13.mp4', eps_des: 'نساء المدينة وكشف الحقيقة.' },
            { num: 14, title: 'امرأة العزيز - ج 4', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Women_Stories%20from_Quran/Women_Stories_from_Quran_eps14.mp4', eps_des: 'توبة زليخا وإيمانها بالله.' },
            { num: 15, title: 'السيدتان سارة و هاجر - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Women_Stories%20from_Quran/Women_Stories_from_Quran_eps15.mp4', eps_des: 'قصة سارة وهاجر مع إبراهيم.' },
            { num: 16, title: 'السيدتان سارة و هاجر - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Women_Stories%20from_Quran/Women_Stories_from_Quran_eps16.mp4', eps_des: 'صبر هاجر في الصحراء.' },
            { num: 17, title: 'السيدتان سارة و هاجر - ج 3', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Women_Stories%20from_Quran/Women_Stories_from_Quran_eps17.mp4', eps_des: 'معجزة زمزم وإيمان سارة.' },
            { num: 18, title: 'السيدة مريم - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Women_Stories%20from_Quran/Women_Stories_from_Quran_eps18.mp4', eps_des: 'قصة مريم وعبادتها لله.' },
            { num: 19, title: 'السيدة مريم - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Women_Stories%20from_Quran/Women_Stories_from_Quran_eps19.mp4', eps_des: 'بشارة مريم بعيسى المسيح.' },
            { num: 20, title: 'السيدة مريم - ج 3', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Women_Stories%20from_Quran/Women_Stories_from_Quran_eps20.mp4', eps_des: 'صبر مريم أمام الاتهامات.' },
            { num: 21, title: 'زوجة أيوب - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Women_Stories%20from_Quran/Women_Stories_from_Quran_eps21.mp4', eps_des: 'قصة زوجة أيوب وصبرها.' },
            { num: 22, title: 'زوجة أيوب - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Women_Stories%20from_Quran/Women_Stories_from_Quran_eps22.mp4', eps_des: 'تحديات البلاء مع أيوب.' },
            { num: 23, title: 'زوجة أيوب - ج 3', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Women_Stories%20from_Quran/Women_Stories_from_Quran_eps23.mp4', eps_des: 'شفاء أيوب وعبرة الصبر.' },
            { num: 24, title: 'الملكة بلقيس - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Women_Stories%20from_Quran/Women_Stories_from_Quran_eps24.mp4', eps_des: 'قصة بلقيس ملكة سبأ.' },
            { num: 25, title: 'الملكة بلقيس - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Women_Stories%20from_Quran/Women_Stories_from_Quran_eps25.mp4', eps_des: 'دعوة سليمان لبلقيس.' },
            { num: 26, title: 'الملكة بلقيس - ج 3', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Women_Stories%20from_Quran/Women_Stories_from_Quran_eps26.mp4', eps_des: 'إيمان بلقيس بالله.' },
            { num: 27, title: 'أم عمار', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Women_Stories%20from_Quran/Women_Stories_from_Quran_eps27.mp4', eps_des: 'قصة أم عمار وإسلامها المبكر.' },
            { num: 28, title: 'أم جميل - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Women_Stories%20from_Quran/Women_Stories_from_Quran_eps28.mp4', eps_des: 'قصة أم جميل وعدائها.' },
            { num: 29, title: 'أم كلثوم بنت عقبة', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Women_Stories%20from_Quran/Women_Stories_from_Quran_eps29.mp4', eps_des: 'هجرة أم كلثوم وإيمانها.' },
            { num: 30, title: 'أم جميل - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Women_Stories%20from_Quran/Women_Stories_from_Quran_eps30.mp4', eps_des: 'نهاية أم جميل كعبرة.' }
        ]
    },

    // قصص العجائب في القرآن
    2: {
        title: 'قصص العجائب في القرآن',
        description: 'عجائب قرآنية مشوقة تعلم الأطفال العبر والإيمان بأسلوب ممتع.',
        episodes: [
            { num: 0, title: 'مقدمه الحلقه', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_Stories_from_Quran_intro.mp4', eps_des: 'لغز سرقة الدرع وكشف الحقيقة بالعدل.' },
            { num: '00', title: 'خاتمه الحلقه', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_Stories_from_Quran_outro.mp4', eps_des: 'لغز سرقة الدرع وكشف الحقيقة بالعدل.' },
            { num: 1, title: 'الدرع المسروقة - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_Stories_from_Quran_eps1.mp4', eps_des: 'لغز سرقة الدرع وكشف الحقيقة بالعدل.' },
            { num: 1, title: 'كواليس', duration: '2 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_stories_from_Quran_BTS/Marvellous_stories_from_Quran_eps1.mp4', eps_des: 'كواليس الحلقه.' },
            { num: 2, title: 'الدرع المسروقة - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_Stories_from_Quran_eps2.mp4', eps_des: 'تحقيق في سرقة الدرع بعبرة إيمانية.' },
            { num: 2, title: 'كواليس', duration: '2 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_stories_from_Quran_BTS/Marvellous_stories_from_Quran_eps2.mp4', eps_des: 'كواليس الحلقه.' },
            { num: 3, title: 'الدرع المسروقة - ج 3', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_Stories_from_Quran_eps3.mp4', eps_des: 'نهاية لغز الدرع وعدالة الله الكاملة.' },
            { num: 3, title: 'كواليس', duration: '2 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_stories_from_Quran_BTS/Marvellous_stories_from_Quran_eps3.mp4', eps_des: 'كواليس الحلقه.' },
            { num: 4, title: 'الثلاثة الذين خلفوا - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_Stories_from_Quran_eps4.mp4', eps_des: 'قصة الثلاثة وتخلفهم عن الجهاد.' },
            { num: 4, title: 'كواليس', duration: '2 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_stories_from_Quran_BTS/Marvellous_stories_from_Quran_eps4.mp4', eps_des: 'كواليس الحلقه.' },
            { num: 5, title: 'الثلاثة الذين خلفوا - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_Stories_from_Quran_eps5.mp4', eps_des: 'ندم الثلاثة وتحديات التوبة.' },
            { num: 5, title: 'كواليس', duration: '2 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_stories_from_Quran_BTS/Marvellous_stories_from_Quran_eps5.mp4', eps_des: 'كواليس الحلقه.' },
            { num: 6, title: 'الثلاثة الذين خلفوا - ج 3', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_Stories_from_Quran_eps6.mp4', eps_des: 'غفران الله للثلاثة بعبرة الصبر.' },
            { num: 6, title: 'كواليس', duration: '2 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_stories_from_Quran_BTS/Marvellous_stories_from_Quran_eps6.mp4', eps_des: 'كواليس الحلقه.' },
            { num: 7, title: 'المبيت في الغار - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_Stories_from_Quran_eps7.mp4', eps_des: 'هجرة النبي وأبو بكر للغار.' },
            { num: 7, title: 'كواليس', duration: '2 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_stories_from_Quran_BTS/Marvellous_stories_from_Quran_eps7.mp4', eps_des: 'كواليس الحلقه.' },
            { num: 8, title: 'المبيت في الغار - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_Stories_from_Quran_eps8.mp4', eps_des: 'معجزة الغار وصبر أبو بكر.' },
            { num: 8, title: 'كواليس', duration: '2 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_stories_from_Quran_BTS/Marvellous_stories_from_Quran_eps8.mp4', eps_des: 'كواليس الحلقه.' },
            { num: 9, title: 'المبيت في الغار - ج 3', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_Stories_from_Quran_eps9.mp4', eps_des: 'حماية الله للنبي في الغار.' },
            { num: 9, title: 'كواليس', duration: '2 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_stories_from_Quran_BTS/Marvellous_stories_from_Quran_eps9.mp4', eps_des: 'كواليس الحلقه.' },
            { num: 10, title: 'المبيت في الغار - ج 4', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_Stories_from_Quran_eps10.mp4', eps_des: 'نهاية قصة الغار بعبرة إيمانية.' },
            { num: 10, title: 'كواليس', duration: '2 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_stories_from_Quran_BTS/Marvellous_stories_from_Quran_eps10.mp4', eps_des: 'كواليس الحلقه.' },
            { num: 11, title: 'القرد العادل', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_Stories_from_Quran_eps11.mp4', eps_des: 'عجيبة القرد وعدالته في القضاء.' },
            { num: 11, title: 'كواليس', duration: '2 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_stories_from_Quran_BTS/Marvellous_stories_from_Quran_eps11.mp4', eps_des: 'كواليس الحلقه.' },
            { num: 12, title: 'بائعة اللبن', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_Stories_from_Quran_eps12.mp4', eps_des: 'قصة بائعة اللبن وأمانتها الربانية.' },
            { num: 12, title: 'كواليس', duration: '2 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_stories_from_Quran_BTS/Marvellous_stories_from_Quran_eps12.mp4', eps_des: 'كواليس الحلقه.' },
            { num: 13, title: 'أصحاب الرس - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_Stories_from_Quran_eps13.mp4', eps_des: 'قصة أصحاب الرس ونبيهم الداعي.' },
            { num: 13, title: 'كواليس', duration: '2 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_stories_from_Quran_BTS/Marvellous_stories_from_Quran_eps13.mp4', eps_des: 'كواليس الحلقه.' },
            { num: 14, title: 'أصحاب الرس - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_Stories_from_Quran_eps14.mp4', eps_des: 'تحديات أصحاب الرس في الإيمان.' },
            { num: 14, title: 'كواليس', duration: '2 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_stories_from_Quran_BTS/Marvellous_stories_from_Quran_eps14.mp4', eps_des: 'كواليس الحلقه.' },
            { num: 15, title: 'أصحاب الرس - ج 3', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_Stories_from_Quran_eps15.mp4', eps_des: 'عقاب أصحاب الرس بعبرة.' },
            { num: 15, title: 'كواليس', duration: '2 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_stories_from_Quran_BTS/Marvellous_stories_from_Quran_eps15.mp4', eps_des: 'كواليس الحلقه.' },
            { num: 16, title: 'بلعام بن باعوراء - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_Stories_from_Quran_eps16.mp4', eps_des: 'قصة بلعام ودعوته للشر.' },
            { num: 16, title: 'كواليس', duration: '2 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_stories_from_Quran_BTS/Marvellous_stories_from_Quran_eps16.mp4', eps_des: 'كواليس الحلقه.' },
            { num: 17, title: 'بلعام بن باعوراء - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_Stories_from_Quran_eps17.mp4', eps_des: 'معجزات بلعام وغروره.' },
            { num: 17, title: 'كواليس', duration: '2 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_stories_from_Quran_BTS/Marvellous_stories_from_Quran_eps17.mp4', eps_des: 'كواليس الحلقه.' },
            { num: 18, title: 'بلعام بن باعوراء - ج 3', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_Stories_from_Quran_eps18.mp4', eps_des: 'نهاية بلعام كعبرة من الغرور.' },
            { num: 18, title: 'كواليس', duration: '2 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_stories_from_Quran_BTS/Marvellous_stories_from_Quran_eps18.mp4', eps_des: 'كواليس الحلقه.' },
            { num: 19, title: 'مؤمن آل ياسين - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq//Marvellous_Stories_from_Quran/Marvellous_Stories_from_Quran_eps19.mp4', eps_des: 'قصة مؤمن ياسين ودعوته.' },
            { num: 19, title: 'كواليس', duration: '2 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_stories_from_Quran_BTS/Marvellous_stories_from_Quran_eps19.mp4', eps_des: 'كواليس الحلقه.' },
            { num: 20, title: 'مؤمن آل ياسين - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_Stories_from_Quran_eps20.mp4', eps_des: 'صبر مؤمن ياسين أمام الكفر.' },
            { num: 20, title: 'كواليس', duration: '2 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_stories_from_Quran_BTS/Marvellous_stories_from_Quran_eps20.mp4', eps_des: 'كواليس الحلقه.' },
            { num: 21, title: 'الغنم و الحديقة - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_Stories_from_Quran_eps21.mp4', eps_des: 'حكمة سليمان في قضية الغنم.' },
            { num: 21, title: 'كواليس', duration: '2 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_stories_from_Quran_BTS/Marvellous_stories_from_Quran_eps21.mp4', eps_des: 'كواليس الحلقه.' },
            { num: 22, title: 'الأقرع و الأبصر و الأعمى - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_Stories_from_Quran_eps22.mp4', eps_des: 'عجيبة الثلاثة واختبارهم.' },
            { num: 22, title: 'كواليس', duration: '2 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_stories_from_Quran_BTS/Marvellous_stories_from_Quran_eps22.mp4', eps_des: 'كواليس الحلقه.' },
            { num: 23, title: 'الأقرع و الأبصر و الأعمى - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_Stories_from_Quran_eps23.mp4', eps_des: 'عبرة من قصة الثلاثة في الإيمان.' },
            { num: 23, title: 'كواليس', duration: '2 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_stories_from_Quran_BTS/Marvellous_stories_from_Quran_eps23.mp4', eps_des: 'كواليس الحلقه.' },
            { num: 24, title: 'الألف دينار و الخشبة - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_Stories_from_Quran_eps24.mp4', eps_des: 'قصة الألف دينار ومعجزة الله.' },
            { num: 24, title: 'كواليس', duration: '2 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_stories_from_Quran_BTS/Marvellous_stories_from_Quran_eps24.mp4', eps_des: 'كواليس الحلقه.' },
            { num: 25, title: 'الألف دينار و الخشبة - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_Stories_from_Quran_eps25.mp4', eps_des: 'كيف وصل الدينار بالخشبة.' },
            { num: 25, title: 'كواليس', duration: '2 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_stories_from_Quran_BTS/Marvellous_stories_from_Quran_eps25.mp4', eps_des: 'كواليس الحلقه.' },
            { num: 26, title: 'برصيصا - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_Stories_from_Quran_eps26.mp4', eps_des: 'قصة برصيصا العابد وغروره.' },
            { num: 26, title: 'كواليس', duration: '2 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_stories_from_Quran_BTS/Marvellous_stories_from_Quran_eps26.mp4', eps_des: 'كواليس الحلقه.' },
            { num: 27, title: 'برصيصا - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_Stories_from_Quran_eps27.mp4', eps_des: 'إغواء برصيصا وندمه.' },
            { num: 27, title: 'كواليس', duration: '2 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_stories_from_Quran_BTS/Marvellous_stories_from_Quran_eps27.mp4', eps_des: 'كواليس الحلقه.' },
            { num: 28, title: 'برصيصا - ج 3', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_Stories_from_Quran_eps28.mp4', eps_des: 'نهاية برصيصا بعبرة من الشيطان.' },
            { num: 28, title: 'كواليس', duration: '2 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_stories_from_Quran_BTS/Marvellous_stories_from_Quran_eps28.mp4', eps_des: 'كواليس الحلقه.' },
            { num: 29, title: 'جرة الذهب', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_Stories_from_Quran_eps29.mp4', eps_des: 'عجيبة جرة الذهب والكرم.' },
            { num: 29, title: 'كواليس', duration: '2 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_stories_from_Quran_BTS/Marvellous_stories_from_Quran_eps29.mp4', eps_des: 'كواليس الحلقه.' },
            { num: 30, title: 'تتر النهاية', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_Stories_from_Quran_eps30.mp4', eps_des: 'خاتمة مشوقة لعجائب القرآن.' },
            { num: 30, title: 'كواليس', duration: '2 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Marvellous_Stories_from_Quran/Marvellous_stories_from_Quran_BTS/Marvellous_stories_from_Quran_eps30.mp4', eps_des: 'كواليس الحلقه.' },
        ],
    },

    // قصص الآيات في القرآن
    3: {
        title: 'قصص الآيات في القرآن',
        description: 'قصص نزول الآيات مع الصحابة، تعلم العبر الإيمانية للأطفال بأسلوب مشوق.',
        episodes: [
            { num: 0, title: 'مقدمه الحلقه', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Verses_stories_from_Quran/Verses_stories_from_Quran_intro.mp4', eps_des: '' },
            { num: '00', title: 'خاتمه الحلقه', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Verses_stories_from_Quran/Verses_stories_from_Quran_outro.mp4', eps_des: '' },
            { num: 1, title: 'حاطب بن أبي بلتعة - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Verses_stories_from_Quran/Verses_stories_from_Quran_eps1.mp4', eps_des: 'قصة حاطب وسر رسالته السرية.' },
            { num: 2, title: 'حاطب بن أبي بلتعة - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Verses_stories_from_Quran/Verses_stories_from_Quran_eps2.mp4', eps_des: 'توبة حاطب وغفران الله له.' },
            { num: 3, title: 'النجاشي - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Verses_stories_from_Quran/Verses_stories_from_Quran_eps3.mp4', eps_des: 'قصة النجاشي ودعمه للمسلمين.' },
            { num: 4, title: 'النجاشي - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Verses_stories_from_Quran/Verses_stories_from_Quran_eps4.mp4', eps_des: 'إسلام النجاشي وصبره أمام الاضطهاد.' },
            { num: 5, title: 'النجاشي - ج 3', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Verses_stories_from_Quran/Verses_stories_from_Quran_eps5.mp4', eps_des: 'نهاية النجاشي كمثال للعدل.' },
            { num: 6, title: 'عياش بن أبي ربيعة - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Verses_stories_from_Quran/Verses_stories_from_Quran_eps6.mp4', eps_des: 'هجرة عياش وتحديات الإيمان.' },
            { num: 7, title: 'عياش بن أبي ربيعة - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Verses_stories_from_Quran/Verses_stories_from_Quran_eps7.mp4', eps_des: 'نجاة عياش بعبرة من الولاء.' },
            { num: 8, title: 'وحشي - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Verses_stories_from_Quran/Verses_stories_from_Quran_eps8.mp4', eps_des: 'قصة وحشي قاتل حمزة.' },
            { num: 9, title: 'وحشي - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Verses_stories_from_Quran/Verses_stories_from_Quran_eps9.mp4', eps_des: 'ندم وحشي وإسلامه.' },
            { num: 10, title: 'وحشي - ج 3', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Verses_stories_from_Quran/Verses_stories_from_Quran_eps10.mp4', eps_des: 'توبة وحشي وغفران الله.' },
            { num: 11, title: 'سلمان الفارسي - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Verses_stories_from_Quran/Verses_stories_from_Quran_eps11.mp4', eps_des: 'بحث سلمان عن الحقيقة.' },
            { num: 12, title: 'سلمان الفارسي - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Verses_stories_from_Quran/Verses_stories_from_Quran_eps12.mp4', eps_des: 'هجرة سلمان للإسلام.' },
            { num: 13, title: 'سلمان الفارسي - ج 3', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Verses_stories_from_Quran/Verses_stories_from_Quran_eps13.mp4', eps_des: 'مساهمة سلمان في الإسلام.' },
            { num: 14, title: 'مرثد بن أبي مرثد - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Verses_stories_from_Quran/Verses_stories_from_Quran_eps14.mp4', eps_des: 'قصة مرثد وإنقاذ الأسير.' },
            { num: 15, title: 'مرثد بن أبي مرثد - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Verses_stories_from_Quran/Verses_stories_from_Quran_eps15.mp4', eps_des: 'تحديات مرثد في الإيمان.' },
            { num: 16, title: 'مرثد بن أبي مرثد - ج 3', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Verses_stories_from_Quran/Verses_stories_from_Quran_eps16.mp4', eps_des: 'شهادة مرثد بعبرة الولاء.' },
            { num: 17, title: 'خولة بنت ثعلبة - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Verses_stories_from_Quran/Verses_stories_from_Quran_eps17.mp4', eps_des: 'قصة خولة وشكواها للنبي.' },
            { num: 18, title: 'خولة بنت ثعلبة - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Verses_stories_from_Quran/Verses_stories_from_Quran_eps18.mp4', eps_des: 'نزول آية لخولة في الطلاق.' },
            { num: 19, title: 'صهيب الرومي - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Verses_stories_from_Quran/Verses_stories_from_Quran_eps19.mp4', eps_des: 'هجرة صهيب وفقدانه ماله.' },
            { num: 20, title: 'صهيب الرومي - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Verses_stories_from_Quran/Verses_stories_from_Quran_eps20.mp4', eps_des: 'توبة صهيب وإيمانه القوي.' },
            { num: 21, title: 'أم شريك - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Verses_stories_from_Quran/Verses_stories_from_Quran_eps21.mp4', eps_des: 'قصة أم شريك ودعوتها للإسلام.' },
            { num: 22, title: 'أم شريك - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Verses_stories_from_Quran/Verses_stories_from_Quran_eps22.mp4', eps_des: 'صبر أم شريك أمام الاضطهاد.' },
            { num: 23, title: 'أم شريك - ج 3', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Verses_stories_from_Quran/Verses_stories_from_Quran_eps23.mp4', eps_des: 'مساهمة أم شريك في الدعوة.' },
            { num: 24, title: 'عثمان بن طلحة - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Verses_stories_from_Quran/Verses_stories_from_Quran_eps24.mp4', eps_des: 'قصة عثمان حارس الكعبة.' },
            { num: 25, title: 'عثمان بن طلحة - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq//Verses_stories_from_Quran/Verses_stories_from_Quran_eps25.mp4', eps_des: 'إسلام عثمان وتسليم المفتاح.' },
            { num: 26, title: 'عبد الله بن سلام - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Verses_stories_from_Quran/Verses_stories_from_Quran_eps26.mp4', eps_des: 'قصة عبد الله اليهودي وإسلامه.' },
            { num: 27, title: 'عبد الله بن سلام - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Verses_stories_from_Quran/Verses_stories_from_Quran_eps27.mp4', eps_des: 'مساهمة عبد الله في الإسلام.' },
            { num: 28, title: 'معاذ بن جبل - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Verses_stories_from_Quran/Verses_stories_from_Quran_eps28.mp4', eps_des: 'قصة معاذ وعلمه بالقرآن.' },
            { num: 29, title: 'معاذ بن جبل - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Verses_stories_from_Quran/Verses_stories_from_Quran_eps29.mp4', eps_des: 'دعوة معاذ في اليمن.' },
            { num: 30, title: 'معاذ بن جبل - ج 3', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Verses_stories_from_Quran/Verses_stories_from_Quran_eps30.mp4', eps_des: 'شهادة معاذ بعبرة العلم.' }
        ]
    },

    // قصص الإنسان في القرآن
    4: {
        title: 'قصص الإنسان في القرآن',
        description: 'قصص بشرية قرآنية تعلم العدل والصبر والإيمان للأطفال بأسلوب مثير.',
        episodes: [
            { num: 0, title: 'المقدمه', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Human_Stories_from_Quran/Human_Stories_from_Quran_intro.mp4', eps_des: 'مقدمه الحلقه' },
            { num: '00', title: 'الخاتمه', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Human_Stories_from_Quran/Human_Stories_from_Quran_otrro.mp4', eps_des: 'خاتمه الحلقه' },
            { num: 1, title: 'أصحاب الأخدود - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Human_Stories_from_Quran/Human_Stories_from_Quran_eps1.mp4', eps_des: 'قصة أصحاب الأخدود وصبرهم على الإيمان.' },
            { num: 2, title: 'أصحاب الأخدود - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Human_Stories_from_Quran/Human_Stories_from_Quran_eps2.mp4', eps_des: 'تحديات أصحاب الأخدود أمام الاضطهاد.' },
            { num: 3, title: 'أصحاب الأخدود - ج 3', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Human_Stories_from_Quran/Human_Stories_from_Quran_eps3.mp4', eps_des: 'نهاية أصحاب الأخدود بعبرة الإيمان.' },
            { num: 4, title: 'طالوت و جالوت - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Human_Stories_from_Quran/Human_Stories_from_Quran_eps4.mp4', eps_des: 'قصة طالوت واختياره ملكاً.' },
            { num: 5, title: 'طالوت و جالوت - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Human_Stories_from_Quran/Human_Stories_from_Quran_eps5.mp4', eps_des: 'معركة طالوت مع جالوت.' },
            { num: 6, title: 'طالوت و جالوت - ج 3', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Human_Stories_from_Quran/Human_Stories_from_Quran_eps6.mp4', eps_des: 'انتصار داود على جالوت بعبرة.' },
            { num: 7, title: 'قارون - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Human_Stories_from_Quran/Human_Stories_from_Quran_eps7.mp4', eps_des: 'قصة قارون وغناه الزائد.' },
            { num: 8, title: 'قارون - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Human_Stories_from_Quran/Human_Stories_from_Quran_eps8.mp4', eps_des: 'غرور قارون أمام موسى.' },
            { num: 9, title: 'قارون - ج 3', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Human_Stories_from_Quran/Human_Stories_from_Quran_eps9.mp4', eps_des: 'عقاب قارون بعبرة التواضع.' },
            { num: 10, title: 'ذو القرنين - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Human_Stories_from_Quran/Human_Stories_from_Quran_eps10.mp4', eps_des: 'قصة ذو القرنين وفتوحاته.' },
            { num: 11, title: 'ذو القرنين - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Human_Stories_from_Quran/Human_Stories_from_Quran_eps11.mp4', eps_des: 'بناء السد ضد يأجوج ومأجوج.' },
            { num: 12, title: 'ذو القرنين - ج 3', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Human_Stories_from_Quran/Human_Stories_from_Quran_eps12.mp4', eps_des: 'عبرة ذو القرنين في العدل.' },
            { num: 13, title: 'أصحاب الجنة - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Human_Stories_from_Quran/Human_Stories_from_Quran_eps13.mp4', eps_des: 'قصة أصحاب الجنة وغناهم.' },
            { num: 14, title: 'أصحاب الجنة - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Human_Stories_from_Quran/Human_Stories_from_Quran_eps14.mp4', eps_des: 'حرق الجنة بعبرة البخل.' },
            { num: 15, title: 'أصحاب الجنة - ج 3', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Human_Stories_from_Quran/Human_Stories_from_Quran_eps15.mp4', eps_des: 'توبة أصحاب الجنة وكرم الله.' },
            { num: 16, title: 'سيدنا الخضر - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Human_Stories_from_Quran/Human_Stories_from_Quran_eps16.mp4', eps_des: 'لقاء موسى بالخضر.' },
            { num: 17, title: 'سيدنا الخضر - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Human_Stories_from_Quran/Human_Stories_from_Quran_eps17.mp4', eps_des: 'أسرار أفعال الخضر مع موسى.' },
            { num: 18, title: 'سيدنا الخضر - ج 3', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Human_Stories_from_Quran/Human_Stories_from_Quran_eps18.mp4', eps_des: 'عبرة الخضر في الصبر والحكمة.' },
            { num: 19, title: 'سيدنا الخضر - ج 4', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Human_Stories_from_Quran/Human_Stories_from_Quran_eps19.mp4', eps_des: 'نهاية قصة الخضر بعبرة العلم.' },
            { num: 20, title: 'السيل العرم - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Human_Stories_from_Quran/Human_Stories_from_Quran_eps20.mp4', eps_des: 'قصة سد مأرب والسيل العرم.' },
            { num: 21, title: 'السيل العرم - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Human_Stories_from_Quran/Human_Stories_from_Quran_eps21.mp4', eps_des: 'فساد أهل مأرب وانهيار السد.' },
            { num: 22, title: 'السيل العرم - ج 3', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Human_Stories_from_Quran/Human_Stories_from_Quran_eps22.mp4', eps_des: 'عقاب السيل العرم بعبرة الكفر.' },
            { num: 23, title: 'السامري - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Human_Stories_from_Quran/Human_Stories_from_Quran_eps23.mp4', eps_des: 'قصة السامري وصنع العجل.' },
            { num: 24, title: 'السامري - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Human_Stories_from_Quran/Human_Stories_from_Quran_eps24.mp4', eps_des: 'إغواء السامري لبني إسرائيل.' },
            { num: 25, title: 'السامري - ج 3', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Human_Stories_from_Quran/Human_Stories_from_Quran_eps25.mp4', eps_des: 'عقاب السامري بعبرة الشرك.' },
            { num: 26, title: 'النمرود - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Human_Stories_from_Quran/Human_Stories_from_Quran_eps26.mp4', eps_des: 'غرور النمرود أمام إبراهيم.' },
            { num: 27, title: 'النمرود - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Human_Stories_from_Quran/Human_Stories_from_Quran_eps27.mp4', eps_des: 'هزيمة النمرود بالبعوض.' },
            { num: 28, title: 'صاحب الجنتين - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Human_Stories_from_Quran/Human_Stories_from_Quran_eps28.mp4', eps_des: 'قصة صاحب الجنتين وغناه.' },
            { num: 29, title: 'صاحب الجنتين - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Human_Stories_from_Quran/Human_Stories_from_Quran_eps29.mp4', eps_des: 'غرور صاحب الجنتين أمام صديقه.' },
            { num: 30, title: 'صاحب الجنتين - ج 3', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Human_Stories_from_Quran/Human_Stories_from_Quran_eps30.mp4', eps_des: 'عقاب صاحب الجنتين بعبرة التواضع.' }
        ]
    },

    // قصص الحيوان في القرآن
    5: {
        title: 'قصص الحيوان في القرآن',
        description: 'قصص حيوانات قرآنية مشوقة تعلم الأطفال دور الحيوانات في الرسالات الإلهية بأسلوب ممتع.',
        episodes: [
            { num: 0, title: 'المقدمه', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Animal_Stories_from_Quran/Animal_Stories_from_Quran_intro.mp4', eps_des: 'مقدمه الحلقه' },
            { num: '00', title: 'الخاتمه', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Animal_Stories_from_Quran/Animal_Stories_from_Quran_outro.mp4', eps_des: 'خاتمه الحلقه' },
            { num: 1, title: 'غراب إبني آدم - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Animal_Stories_from_Quran/Animal_Stories_from_Quran_eps1.mp4', eps_des: 'دور الغراب في دفن هابيل.' },
            { num: 2, title: 'غراب إبني آدم - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Animal_Stories_from_Quran/Animal_Stories_from_Quran_eps2.mp4', eps_des: 'عبرة الغراب في تعليم الدفن.' },
            { num: 3, title: 'ناقة صالح - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Animal_Stories_from_Quran/Animal_Stories_from_Quran_eps3.mp4', eps_des: 'معجزة الناقة لقوم ثمود.' },
            { num: 4, title: 'ناقة صالح - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Animal_Stories_from_Quran/Animal_Stories_from_Quran_eps4.mp4', eps_des: 'عقاب قوم صالح لقتل الناقة.' },
            { num: 5, title: 'طير إبراهيم - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Animal_Stories_from_Quran/Animal_Stories_from_Quran_eps5.mp4', eps_des: 'معجزة إحياء الطيور لإبراهيم.' },
            { num: 6, title: 'طير إبراهيم - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Animal_Stories_from_Quran/Animal_Stories_from_Quran_eps6.mp4', eps_des: 'إيمان إبراهيم بإحياء الطيور.' },
            { num: 7, title: 'ذئب يوسف - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Animal_Stories_from_Quran/Animal_Stories_from_Quran_eps7.mp4', eps_des: 'كذب إخوة يوسف عن الذئب.' },
            { num: 8, title: 'ذئب يوسف - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Animal_Stories_from_Quran/Animal_Stories_from_Quran_eps8.mp4', eps_des: 'عبرة الذئب في قصة يوسف.' },
            { num: 9, title: 'حوت يونس - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Animal_Stories_from_Quran/Animal%20Stories%20From%20Quran%20Eps9.mp4', eps_des: 'ابتلاع الحوت ليونس.' },
            { num: 10, title: 'حوت يونس - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Animal_Stories_from_Quran/Animal_Stories_from_Quran_eps10.mp4', eps_des: 'نجاة يونس من بطن الحوت.' },
            { num: 11, title: 'عصا موسى - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Animal_Stories_from_Quran/Animal_Stories_from_Quran_eps11.mp4', eps_des: 'تحول العصا إلى حية أمام فرعون.' },
            { num: 12, title: 'عصا موسى - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Animal_Stories_from_Quran/Animal_Stories_from_Quran_eps12.mp4', eps_des: 'معجزات العصا في قصة موسى.' },
            { num: 13, title: 'عصا موسى - ج 3', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Animal_Stories_from_Quran/Animal_Stories_from_Quran_eps13.mp4', eps_des: 'دور العصا في شق البحر.' },
            { num: 14, title: 'بقرة بني إسرائيل - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Animal_Stories_from_Quran/Animal_Stories_from_Quran_eps14.mp4', eps_des: 'أمر الله بذبح البقرة.' },
            { num: 15, title: 'بقرة بني إسرائيل - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Animal_Stories_from_Quran/Animal_Stories_from_Quran_eps15.mp4', eps_des: 'كشف القتيل بضرب البقرة.' },
            { num: 16, title: 'أصحاب السبت - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Animal_Stories_from_Quran/Animal_Stories_from_Quran_eps16.mp4', eps_des: 'عقاب اليهود بتحويلهم قردة.' },
            { num: 17, title: 'أصحاب السبت - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Animal_Stories_from_Quran/Animal_Stories_from_Quran_eps17.mp4', eps_des: 'عبرة أصحاب السبت في الطاعة.' },
            { num: 18, title: 'نملة سليمان - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Animal_Stories_from_Quran/Animal_Stories_from_Quran_eps18.mp4', eps_des: 'حذر النملة من جيش سليمان.' },
            { num: 19, title: 'نملة سليمان - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Animal_Stories_from_Quran/Animal_Stories_from_Quran_eps19.mp4', eps_des: 'حكمة النملة وعبرتها.' },
            { num: 20, title: 'هدهد سليمان - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Animal_Stories_from_Quran/Animal_Stories_from_Quran_eps20.mp4', eps_des: 'اكتشاف الهدهد ملكة سبأ.' },
            { num: 21, title: 'هدهد سليمان - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Animal_Stories_from_Quran/Animal_Stories_from_Quran_eps21.mp4', eps_des: 'دعوة سليمان لملكة سبأ بالهدهد.' },
            { num: 22, title: 'دابة الأرض', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Animal_Stories_from_Quran/Animal_Stories_from_Quran_eps22.mp4', eps_des: 'دور دابة الأرض في آخر الزمان.' },
            { num: 23, title: 'حمار العزير - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Animal_Stories_from_Quran/Animal_Stories_from_Quran_eps23.mp4', eps_des: 'إحياء عزير وحماره بعد موته.' },
            { num: 24, title: 'حمار العزير - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Animal_Stories_from_Quran/Animal_Stories_from_Quran_eps24.mp4', eps_des: 'عبرة إحياء الحمار في القيامة.' },
            { num: 25, title: 'كلب أهل الكهف - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Animal_Stories_from_Quran/Animal_Stories_from_Quran_eps25.mp4', eps_des: 'حراسة الكلب لأصحاب الكهف.' },
            { num: 26, title: 'كلب أهل الكهف - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Animal_Stories_from_Quran/Animal_Stories_from_Quran_eps26.mp4', eps_des: 'معجزة نوم أصحاب الكهف والكلب.' },
            { num: 27, title: 'طين عيسى', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Animal_Stories_from_Quran/Animal_Stories_from_Quran_eps27.mp4', eps_des: 'خلق عيسى الطيور من الطين.' },
            { num: 28, title: 'فيل أبرهة و الطير الأبابيل - ج 1', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Animal_Stories_from_Quran/Animal_Stories_from_Quran_eps28.mp4', eps_des: 'هجوم أبرهة بالفيل على الكعبة.' },
            { num: 29, title: 'فيل أبرهة و الطير الأبابيل - ج 2', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Animal_Stories_from_Quran/Animal_Stories_from_Quran_eps29.mp4', eps_des: 'تدمير الجيش بالطير الأبابيل.' },
            { num: 30, title: 'عنكبوت الغار', duration: '20 دقيقة', video: 'https://file.garden/aYOOHhOBlkBEdoxq/Animal_Stories_from_Quran/Animal_Stories_from_Quran_eps30.mp4', eps_des: 'نسج العنكبوت لحماية النبي.' }
        ]
    },


    // // قصص القرآن بالصلصال
    // 6: {
    //     title: 'قصص القرآن بالصلصال',
    //     description: 'قصص قرآنية مشوقة بالصلصال، تعلم العبر الأخلاقية للأطفال بطريقة فنية.',
    //     episodes: [
    //         { num: 1, title: 'اغنية المقدمة', duration: '20 دقيقة', video: 'vid/Quran_Claymation/Quran_Claymation_eps1.mp4', eps_des: 'مقدمة موسيقية جذابة لقصص القرآن.' },
    //         { num: 2, title: 'اغنية النهاية', duration: '20 دقيقة', video: 'vid/Quran_Claymation/Quran_Claymation_eps2.mp4', eps_des: 'خاتمة موسيقية تعزز العبر الإيمانية.' },
    //         { num: 3, title: 'ذو القرنين', duration: '20 دقيقة', video: 'vid/Quran_Claymation/Quran_Claymation_eps3.mp4', eps_des: 'رحلة ذو القرنين وبناء السد العظيم.' },
    //         { num: 4, title: 'اصحاب الغار', duration: '20 دقيقة', video: 'vid/Quran_Claymation/Quran_Claymation_eps4.mp4', eps_des: 'قصة أصحاب الغار ومعجزة النوم الطويل.' },
    //         { num: 5, title: 'اصحاب السبت', duration: '20 دقيقة', video: 'vid/Quran_Claymation/Quran_Claymation_eps5.mp4', eps_des: 'عقاب أصحاب السبت لمخالفتهم الأمر الإلهي.' },
    //         { num: 6, title: 'السامرى والعجل 1', duration: '20 دقيقة', video: 'vid/Quran_Claymation/Quran_Claymation_eps6.mp4', eps_des: 'صنع السامري للعجل الذهبي الأول.' },
    //         { num: 7, title: 'السامرى والعجل 2', duration: '20 دقيقة', video: 'vid/Quran_Claymation/Quran_Claymation_eps7.mp4', eps_des: 'نهاية قصة السامري وعقاب العجل.' },
    //         { num: 8, title: 'اصحاب الرس', duration: '20 دقيقة', video: 'vid/Quran_Claymation/Quran_Claymation_eps8.mp4', eps_des: 'قصة أصحاب الرس وهلاكهم بالبئر.' },
    //         { num: 9, title: 'البقرة الصفراء', duration: '20 دقيقة', video: 'vid/Quran_Claymation/Quran_Claymation_eps9.mp4', eps_des: 'معجزة البقرة الصفراء وكشف القتل.' },
    //         { num: 10, title: 'اصحاب الايثار', duration: '20 دقيقة', video: 'vid/Quran_Claymation/Quran_Claymation_eps10.mp4', eps_des: 'قصة أصحاب الإيثار والكرم الإلهي.' },
    //         { num: 11, title: 'الاجتهاد', duration: '20 دقيقة', video: 'vid/Quran_Claymation/Quran_Claymation_eps11.mp4', eps_des: 'عبرة الاجتهاد في طلب العلم.' },
    //         { num: 12, title: 'اصحاب الكهف', duration: '20 دقيقة', video: 'vid/Quran_Claymation/Quran_Claymation_eps12.mp4', eps_des: 'قصة أصحاب الكهف والنوم الطويل.' },
    //         { num: 13, title: 'الملك طالوت', duration: '20 دقيقة', video: 'vid/Quran_Claymation/Quran_Claymation_eps13.mp4', eps_des: 'اختيار طالوت ملكًا ومعجزة التابوت.' },
    //         { num: 14, title: 'اصحاب الجنة', duration: '20 دقيقة', video: 'vid/Quran_Claymation/Quran_Claymation_eps14.mp4', eps_des: 'عبرة أصحاب الجنة من البخل.' },
    //         { num: 15, title: 'الفقر', duration: '20 دقيقة', video: 'vid/Quran_Claymation/Quran_Claymation_eps15.mp4', eps_des: 'قصة الفقر واختبار الإيمان.' },
    //         { num: 16, title: 'اصحاب الاخدود', duration: '20 دقيقة', video: 'vid/Quran_Claymation/Quran_Claymation_eps16.mp4', eps_des: 'صبر أصحاب الأخدود أمام النار.' },
    //         { num: 17, title: 'الدعاء', duration: '20 دقيقة', video: 'vid/Quran_Claymation/Quran_Claymation_eps17.mp4', eps_des: 'قوة الدعاء وإجابة الله.' },
    //         { num: 18, title: 'اصحاب القرية 1', duration: '20 دقيقة', video: 'vid/Quran_Claymation/Quran_Claymation_eps18.mp4', eps_des: 'دعوة أصحاب القرية للإيمان.' },
    //         { num: 19, title: 'اصحاب القرية 2', duration: '20 دقيقة', video: 'vid/Quran_Claymation/Quran_Claymation_eps19.mp4', eps_des: 'عقاب أصحاب القرية للكفر.' },
    //         { num: 20, title: 'ابليس والرجل الصالح', duration: '20 دقيقة', video: 'vid/Quran_Claymation/Quran_Claymation_eps20.mp4', eps_des: 'إغواء إبليس للرجل الصالح.' },
    //         { num: 21, title: 'لقمان الحكيم', duration: '20 دقيقة', video: 'vid/Quran_Claymation/Quran_Claymation_eps21.mp4', eps_des: 'حكمة لقمان ونصائحه لابنه.' },
    //         { num: 22, title: 'مؤمن ال فرعون', duration: '20 دقيقة', video: 'vid/Quran_Claymation/Quran_Claymation_eps22.mp4', eps_des: 'إيمان مؤمن آل فرعون سرًا.' },
    //         { num: 23, title: 'موسى والخضر', duration: '20 دقيقة', video: 'vid/Quran_Claymation/Quran_Claymation_eps23.mp4', eps_des: 'لقاء موسى والخضر وأسراره.' },
    //         { num: 24, title: 'قارون', duration: '20 دقيقة', video: 'vid/Quran_Claymation/Quran_Claymation_eps24.mp4', eps_des: 'غرور قارون وخسفه بالأرض.' },
    //         { num: 25, title: 'سبأ', duration: '20 دقيقة', video: 'vid/Quran_Claymation/Quran_Claymation_eps25.mp4', eps_des: 'قصة سبأ وسد مأرب العظيم.' },
    //         { num: 26, title: 'صاحب الجنتين', duration: '20 دقيقة', video: 'vid/Quran_Claymation/Quran_Claymation_eps26.mp4', eps_des: 'عبرة صاحب الجنتين من الكفر.' },
    //         { num: 27, title: 'زينب بنت جحش', duration: '20 دقيقة', video: 'vid/Quran_Claymation/Quran_Claymation_eps27.mp4', eps_des: 'قصة زينب ونزول آية التبني.' }
    //     ]
    // },

    // // قصص الأنبياء بالصلصال
    // 7: {
    //     title: 'قصص الأنبياء بالصلصال',
    //     description: 'قصص الأنبياء بالصلصال، رحلة إيمانية ممتعة للأطفال مع عبر أخلاقية.',
    //     episodes: [
    //         { num: 1, title: 'أغنية المقدمة', duration: '20 دقيقة', video: 'vid/Prophets_Claymation/Prophets_Claymation_eps1.mp4', eps_des: 'مقدمة موسيقية لقصص الأنبياء.' },
    //         { num: 2, title: 'أدم', duration: '20 دقيقة', video: 'vid/Prophets_Claymation/Prophets_Claymation_eps2.mp4', eps_des: 'خلق آدم ودخوله الجنة.' },
    //         { num: 3, title: 'أيوب', duration: '20 دقيقة', video: 'vid/Prophets_Claymation/Prophets_Claymation_eps3.mp4', eps_des: 'صبر أيوب على البلاء والشفاء.' },
    //         { num: 4, title: 'عزير', duration: '20 دقيقة', video: 'vid/Prophets_Claymation/Prophets_Claymation_eps4.mp4', eps_des: 'معجزة إحياء عزير بعد موته.' },
    //         { num: 5, title: 'هود', duration: '20 دقيقة', video: 'vid/Prophets_Claymation/Prophets_Claymation_eps5.mp4', eps_des: 'دعوة هود لقوم عاد وعقابهم.' },
    //         { num: 6, title: 'نوح', duration: '20 دقيقة', video: 'vid/Prophets_Claymation/Prophets_Claymation_eps6.mp4', eps_des: 'بناء سفينة نوح والطوفان.' },
    //         { num: 7, title: 'صالح', duration: '20 دقيقة', video: 'vid/Prophets_Claymation/Prophets_Claymation_eps7.mp4', eps_des: 'معجزة ناقة صالح وعقاب ثمود.' },
    //         { num: 8, title: 'داود', duration: '20 دقيقة', video: 'vid/Prophets_Claymation/Prophets_Claymation_eps8.mp4', eps_des: 'معجزة داود في قتل جالوت.' },
    //         { num: 9, title: 'يونس 1', duration: '20 دقيقة', video: 'vid/Prophets_Claymation/Prophets_Claymation_eps9.mp4', eps_des: 'دعوة يونس وابتلاع الحوت.' },
    //         { num: 10, title: 'يونس 2', duration: '20 دقيقة', video: 'vid/Prophets_Claymation/Prophets_Claymation_eps10.mp4', eps_des: 'توبة يونس ونجاته من الحوت.' },
    //         { num: 11, title: 'عيسى', duration: '20 دقيقة', video: 'vid/Prophets_Claymation/Prophets_Claymation_eps11.mp4', eps_des: 'ولادة عيسى ومعجزاته الإلهية.' },
    //         { num: 12, title: 'ابراهيم', duration: '20 دقيقة', video: 'vid/Prophets_Claymation/Prophets_Claymation_eps12.mp4', eps_des: 'إبراهيم وتحطيم الأصنام.' },
    //         { num: 13, title: 'اسماعيل', duration: '20 دقيقة', video: 'vid/Prophets_Claymation/Prophets_Claymation_eps13.mp4', eps_des: 'قصة إسماعيل وذبح الرؤيا.' },
    //         { num: 14, title: 'شعيب', duration: '20 دقيقة', video: 'vid/Prophets_Claymation/Prophets_Claymation_eps14.mp4', eps_des: 'دعوة شعيب لقوم مدين.' },
    //         { num: 15, title: 'يعقوب', duration: '20 دقيقة', video: 'vid/Prophets_Claymation/Prophets_Claymation_eps15.mp4', eps_des: 'قصة يعقوب وأبنائه.' },
    //         { num: 16, title: 'يوسف', duration: '20 دقيقة', video: 'vid/Prophets_Claymation/Prophets_Claymation_eps16.mp4', eps_des: 'رؤيا يوسف وصبره في السجن.' },
    //         { num: 17, title: 'زكريا', duration: '20 دقيقة', video: 'vid/Prophets_Claymation/Prophets_Claymation_eps17.mp4', eps_des: 'دعاء زكريا لولد يحيى.' },
    //         { num: 18, title: 'سليمان 1', duration: '20 دقيقة', video: 'vid/Prophets_Claymation/Prophets_Claymation_eps18.mp4', eps_des: 'ملك سليمان وتسخير الجن.' },
    //         { num: 19, title: 'سليمان 2', duration: '20 دقيقة', video: 'vid/Prophets_Claymation/Prophets_Claymation_eps19.mp4', eps_des: 'هدهد سليمان وملكة سبأ.' },
    //         { num: 20, title: 'موسى', duration: '20 دقيقة', video: 'vid/Prophets_Claymation/Prophets_Claymation_eps20.mp4', eps_des: 'معجزات موسى أمام فرعون.' },
    //         { num: 21, title: 'سيدنا محمد 1', duration: '20 دقيقة', video: 'vid/Prophets_Claymation/Prophets_Claymation_eps21.mp4', eps_des: 'طفولة النبي محمد صلى الله عليه وسلم.' },
    //         { num: 22, title: 'سيدنا محمد 2', duration: '20 دقيقة', video: 'vid/Prophets_Claymation/Prophets_Claymation_eps22.mp4', eps_des: 'بعثة النبي ودعوته للإسلام.' },
    //         { num: 23, title: 'الحجر الاسود', duration: '20 دقيقة', video: 'vid/Prophets_Claymation/Prophets_Claymation_eps23.mp4', eps_des: 'قصة الحجر الأسود وبناء الكعبة.' },
    //         { num: 24, title: 'غار ثور 1', duration: '20 دقيقة', video: 'vid/Prophets_Claymation/Prophets_Claymation_eps24.mp4', eps_des: 'هجرة النبي لغار ثور.' },
    //         { num: 25, title: 'غار ثور 2', duration: '20 دقيقة', video: 'vid/Prophets_Claymation/Prophets_Claymation_eps25.mp4', eps_des: 'معجزة في غار ثور وحماية الله.' }
    //     ]
    // },

    // // المبشرون بالجنة بالصلصال
    // 8: {
    //     title: 'المبشرون بالجنة بالصلصال',
    //     description: 'قصص العشرة المبشرين بالجنة بالصلصال، قدوة إيمانية ممتعة للأطفال.',
    //     episodes: [
    //         { num: 1, title: 'اغنية المقدمة', duration: '20 دقيقة', video: 'vid/Mubasharoon_Claymation/Mubasharoon_Claymation_eps1.mp4', eps_des: 'مقدمة موسيقية للمبشرين بالجنة.' },
    //         { num: 2, title: 'اغنية النهاية', duration: '20 دقيقة', video: 'vid/Mubasharoon_Claymation/Mubasharoon_Claymation_eps2.mp4', eps_des: 'خاتمة موسيقية تعزز العبر الإيمانية.' },
    //         { num: 3, title: 'ابو بكر الصديق 1', duration: '20 دقيقة', video: 'vid/Mubasharoon_Claymation/Mubasharoon_Claymation_eps3.mp4', eps_des: 'إيمان أبو بكر وصدقه مع النبي.' },
    //         { num: 4, title: 'ابو بكر الصديق 2', duration: '20 دقيقة', video: 'vid/Mubasharoon_Claymation/Mubasharoon_Claymation_eps4.mp4', eps_des: 'مساهمة أبو بكر في الإسلام.' },
    //         { num: 5, title: 'ابو بكر الصديق 3', duration: '20 دقيقة', video: 'vid/Mubasharoon_Claymation/Mubasharoon_Claymation_eps5.mp4', eps_des: 'خلافة أبو بكر وعبرة الصدق.' },
    //         { num: 6, title: 'عمر بن الخطاب 1', duration: '20 دقيقة', video: 'vid/Mubasharoon_Claymation/Mubasharoon_Claymation_eps6.mp4', eps_des: 'إسلام عمر وشجاعته.' },
    //         { num: 7, title: 'عمر بن الخطاب 2', duration: '20 دقيقة', video: 'vid/Mubasharoon_Claymation/Mubasharoon_Claymation_eps7.mp4', eps_des: 'فتوحات عمر وعدالته.' },
    //         { num: 8, title: 'عمر بن الخطاب 3', duration: '20 دقيقة', video: 'vid/Mubasharoon_Claymation/Mubasharoon_Claymation_eps8.mp4', eps_des: 'شهادة عمر بعبرة التقوى.' },
    //         { num: 9, title: 'عثمان بن عفان 1', duration: '20 دقيقة', video: 'vid/Mubasharoon_Claymation/Mubasharoon_Claymation_eps9.mp4', eps_des: 'إسلام عثمان وكرمه.' },
    //         { num: 10, title: 'عثمان بن عفان 2', duration: '20 دقيقة', video: 'vid/Mubasharoon_Claymation/Mubasharoon_Claymation_eps10.mp4', eps_des: 'خلافة عثمان وتجميع القرآن.' },
    //         { num: 11, title: 'على بن ابى طالب 1', duration: '20 دقيقة', video: 'vid/Mubasharoon_Claymation/Mubasharoon_Claymation_eps11.mp4', eps_des: 'إسلام علي وشجاعته في بدر.' },
    //         { num: 12, title: 'على بن ابى طالب 2', duration: '20 دقيقة', video: 'vid/Mubasharoon_Claymation/Mubasharoon_Claymation_eps12.mp4', eps_des: 'خلافة علي وعبرة العدل.' },
    //         { num: 13, title: 'عبد الرحمن بن عوف', duration: '20 دقيقة', video: 'vid/Mubasharoon_Claymation/Mubasharoon_Claymation_eps13.mp4', eps_des: 'كرم عبد الرحمن وتجارته.' },
    //         { num: 14, title: 'ابو عبيدة بن الجراح', duration: '20 دقيقة', video: 'vid/Mubasharoon_Claymation/Mubasharoon_Claymation_eps14.mp4', eps_des: 'شجاعة أبو عبيدة في الفتوحات.' },
    //         { num: 15, title: 'طلحة بن عبيد الله', duration: '20 دقيقة', video: 'vid/Mubasharoon_Claymation/Mubasharoon_Claymation_eps15.mp4', eps_des: 'بطولة طلحة في أحد.' },
    //         { num: 16, title: 'سعد بن ابى وقاص', duration: '20 دقيقة', video: 'vid/Mubasharoon_Claymation/Mubasharoon_Claymation_eps16.mp4', eps_des: 'فتح سعد للعراق ودعوته.' },
    //         { num: 17, title: 'سعيد بن زيد', duration: '20 دقيقة', video: 'vid/Mubasharoon_Claymation/Mubasharoon_Claymation_eps17.mp4', eps_des: 'إيمان سعيد وجهاده.' },
    //         { num: 18, title: 'السيدة أسيا', duration: '20 دقيقة', video: 'vid/Mubasharoon_Claymation/Mubasharoon_Claymation_eps18.mp4', eps_des: 'إيمان آسية زوجة فرعون.' },
    //         { num: 19, title: 'السيدة خديجة', duration: '20 دقيقة', video: 'vid/Mubasharoon_Claymation/Mubasharoon_Claymation_eps19.mp4', eps_des: 'دعم خديجة للنبي.' },
    //         { num: 20, title: 'السيدة فاطمة', duration: '20 دقيقة', video: 'vid/Mubasharoon_Claymation/Mubasharoon_Claymation_eps20.mp4', eps_des: 'قصة فاطمة الزهراء وصبرها.' }
    //     ]
    // }
};